CI - Add benchmark job

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -319,6 +319,55 @@ jobs:
           . venv/bin/activate
           coveralls --rcfile=${{ env.COVERAGERC_FILE }} --service=github
 
+  benchmark-linux:
+    name: Run benchmark tests Python ${{ matrix.python-version }} (Linux)
+    runs-on: ubuntu-latest
+    needs: prepare-tests-linux
+    strategy:
+      fail-fast: false
+      matrix:
+        python-version: [3.8, 3.9]
+    steps:
+      - name: Check out code from GitHub
+        uses: actions/checkout@v2.3.4
+      - name: Set up Python ${{ matrix.python-version }}
+        id: python
+        uses: actions/setup-python@v2.2.1
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Restore Python virtual environment
+        id: cache-venv
+        uses: actions/cache@v2.1.4
+        with:
+          path: venv
+          key: ${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{
+            needs.prepare-tests-linux.outputs.python-key }}
+      - name: Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python venv from cache"
+          exit 1
+      - name: Run pytest
+        run: |
+          . venv/bin/activate
+          pip install pygal
+          pip install -e .
+          pytest --exitfirst \
+            --benchmark-only \
+            --benchmark-autosave \
+            --benchmark-save-data \
+            --benchmark-group-by="group"
+      - name: Create partial artifact name suffix
+        id: artifact-name-suffix
+        run: >-
+          echo "::set-output name=datetime::"$(date "+%Y%m%d_%H%M")
+      - name: Upload benchmark artifact
+        uses: actions/upload-artifact@v2.2.2
+        with:
+          name: benchmark-${{ runner.os }}-${{ matrix.python-version }}_${{
+            steps.artifact-name-suffix.outputs.datetime }}
+          path: .benchmarks/
+
 
   pytest-windows:
     name: Run tests Python ${{ matrix.python-version }} (Windows)
