Make sure only ``main`` can create the primer virtual environment

diff --git a/.github/workflows/primer_comment.yaml b/.github/workflows/primer_comment.yaml
--- a/.github/workflows/primer_comment.yaml
+++ b/.github/workflows/primer_comment.yaml
@@ -13,6 +13,7 @@ on:
       - completed
 
 env:
+  # This needs to be the SAME as in the Main and PR job
   CACHE_VERSION: 20
 
 permissions:
@@ -39,29 +40,19 @@ jobs:
           python-version: "3.10"
 
       # Restore cached Python environment
-      - name: Generate partial Python venv restore key
-        id: generate-python-key
-        run: >-
-          echo "::set-output name=key::venv-${{ env.CACHE_VERSION }}-${{
-            hashFiles('setup.cfg', 'requirements_test.txt', 'requirements_test_min.txt')
-          }}"
       - name: Restore Python virtual environment
         id: cache-venv
         uses: actions/cache@v3.0.7
         with:
           path: venv
-          key: >-
-            ${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{
-            steps.generate-python-key.outputs.key }}
-          restore-keys: |
-            ${{ runner.os }}-${{ steps.python.outputs.python-version }}-venv-${{ env.CACHE_VERSION }}-
-      - name: Create Python virtual environment
+          key:
+            ${{ runner.os }}-${{ steps.python.outputs.python-version }}-venv-primer-${{
+            env.CACHE_VERSION }}
+      - name: Fail job if Python cache restore failed
         if: steps.cache-venv.outputs.cache-hit != 'true'
         run: |
-          python -m venv venv
-          . venv/bin/activate
-          python -m pip install -U pip setuptools wheel
-          pip install -U -r requirements_test.txt
+          echo "Failed to restore Python venv from cache"
+          exit 1
 
       - name: Download outputs
         uses: actions/github-script@v6
diff --git a/.github/workflows/primer_run_pr.yaml b/.github/workflows/primer_run_pr.yaml
--- a/.github/workflows/primer_run_pr.yaml
+++ b/.github/workflows/primer_run_pr.yaml
@@ -24,6 +24,7 @@ concurrency:
   cancel-in-progress: true
 
 env:
+  # This needs to be the SAME as in the Main and comment job
   CACHE_VERSION: 20
 
 jobs:
@@ -49,38 +50,20 @@ jobs:
           node-version: 16
       - run: npm install @octokit/rest
 
-      - name: Get latest astroid commit
-        id: get-astroid-sha
-        run: |
-          curl https://api.github.com/repos/PyCQA/astroid/commits |
-          python -c "import json, sys; print(json.load(sys.stdin)[0]['sha'])" > astroid_sha.txt
-
       # Restore cached Python environment
-      - name: Generate partial Python venv restore key
-        id: generate-python-key
-        run: >-
-          echo "::set-output name=key::venv-${{ env.CACHE_VERSION }}-${{
-            hashFiles('setup.cfg', 'requirements_test.txt', 'requirements_test_min.txt',
-          'astroid_sha.txt') }}"
       - name: Restore Python virtual environment
         id: cache-venv
         uses: actions/cache@v3.0.7
         with:
           path: venv
-          key: >-
-            ${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{
-            steps.generate-python-key.outputs.key }}
-          restore-keys: |
-            ${{ runner.os }}-${{ steps.python.outputs.python-version }}-venv-${{ env.CACHE_VERSION }}-
-      - name: Create Python virtual environment
+          key:
+            ${{ runner.os }}-${{ steps.python.outputs.python-version }}-venv-primer-${{
+            env.CACHE_VERSION }}
+      - name: Fail job if Python cache restore failed
         if: steps.cache-venv.outputs.cache-hit != 'true'
         run: |
-          python -m venv venv
-          . venv/bin/activate
-          python -m pip install -U pip setuptools wheel
-          pip install -U -r requirements_test.txt
-          # Use bleeding-edge astroid
-          pip install git+https://github.com/PyCQA/astroid.git
+          echo "Failed to restore Python venv from cache"
+          exit 1
 
       # Cache primer packages
       - name: Download last 'main' run info
